### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by bdbch** [redxtech/markit#27]
We need two people to work on the design on Figma.

# TASKS

### corporate identity
- [x] logo
- [x] colors

### application
- [ ] views
  - [ ] main view
  - [ ] adding/editing bookmarks view
  - [ ] splash animation
  - [ ] settings view
- [ ] themes
  - [ ] dark
  - [ ] light
  - [ ] gradient
- [ ] new icons instead of icon pack/font
  - [ ] settings icon
  - [ ] folder icon
  - [ ] bookmark icon
  - [ ] login icon
  - [ ] view, add, delete and edit icon
  - [ ] list, grid, details icon

### website
- [ ] splash/info website

**Comment by lostdesign** [comment]
You and me i guess?

**Comment by lostdesign** [comment]
# TASKS

### corporate identity
- [ ] logo
- [ ] colors


### application
- [ ] views
  - [ ] main view
  - [ ] adding/editing bookmarks view
  - [ ] splash animation
  - [ ] settings view
- [ ] themes
  - [ ] dark
  - [ ] light
  - [ ] gradient
- [ ] new icons instead of icon pack/font
  - [ ] settings icon
  - [ ] folder icon
  - [ ] bookmark icon
  - [ ] login icon
  - [ ] view, add, delete and edit icon
  - [ ] list, grid, details icon


### website
- [ ] splash/info website

**Comment by mcastre** [comment]
@bdbch @lostdesign would you guys like some help on the UI design portion of the app?

**Comment by bdbch** [comment]
sure, would be cool.
